# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f6e90d957fc8b63d00d1922eedfd2f4d284efeb32d4d49d0b11d80059e8b3c0b4f2c9d6630ad0c2388efa0dc4e1fabfcc9cd5ce3445e9d5e0d75c2f39275d00

test:
  secret_key_base: 32adc728cfb707d658c5cb0af9bb852669bf90b57fda35c4389cdcfc23d5567b1d3a0e82c5f45b5936ccb7b865a3a509e140f7ec19dbf76ed7d95ccc88d5b435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
